### ISSUE TITLE
Show more data from the connected Thingy:91 devices

### ISSUE THREAD

**Issue by martiles** [NordicPlayground/thingy-rocks-dashboard-aws-js#20]
Could be nice to see some extra data from the connected devices.

**Suggestions:**
- [x] RSRP values (or even simplified, "good, bad, great connection")  
- [x] Utilize CONEVAL values and showcase those in a nice way
  Depends on https://github.com/NordicPlayground/thingy-world-firmware-aws/issues/3
- [x] Remaining Battery % of the Thingy. (or if it's connected?)
- [x] Button press 
- [x] ~~Flip data: depends on https://github.com/NordicPlayground/thingy-world-firmware-aws/issues/4~~

**Comment by coderbyheart** [comment]
Added RSRP visualization: 
![image](https://user-images.githubusercontent.com/188915/205769768-212fdc0b-c104-4cb2-a397-67d81af44749.png)

**Comment by martiles** [comment]
Flip data not necessary since we have button press IMO
