### ISSUE TITLE
[Minor icon bug] GNSS icon disabled

### ISSUE THREAD

**Issue by martiles** [NordicPlayground/thingy-rocks-dashboard-aws-js#29]
![image](https://user-images.githubusercontent.com/16775971/207354677-052bb851-696c-4f64-a038-f2d67303f734.png)
In the table at the right it is shown GNSS two times.
I got GPS fix, but there is still an icon showing that GNSS is disabled (red ring)

**Comment by coderbyheart** [comment]
This happens if the GNSS sampling is disabled AFTER a device has acquired a GPS fix. It's not really a bug, the first icon shows that there is a GNSS location, the second shows that sampling is (now) disabled.
