### ISSUE TITLE
Hide "History location" as default

### ISSUE THREAD

**Issue by martiles** [NordicPlayground/thingy-rocks-dashboard-aws-js#53]
![image](https://github.com/NordicPlayground/thingy-rocks-dashboard-aws-js/assets/16775971/cd1215e6-292b-4ef1-9ed1-8ba5790d4a83)

as default view could we show only the devices that are in the list at the right (Dashboard)?

And in the filter we can have the option:
![image](https://github.com/NordicPlayground/thingy-rocks-dashboard-aws-js/assets/16775971/8bd1bfc6-9f93-468d-a74e-572c0b5b85e4)

"Show historical location data"

(As currently it can be a bit messy on the map)

**Comment by coderbyheart** [comment]
Location history is tracked here: https://github.com/NordicPlayground/thingy-rocks-dashboard-aws-js/issues/34 ... please elaborate there a bit more how you would like that feature to work.

**Comment by coderbyheart** [comment]
> as default view could we show only the devices that are in the list at the right (Dashboard)?

By default all devices are shown. I guess you mean that if "show only favorited devices" is enabled, the map should also only show these locations?
